on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Send a Slack Message using PHP
      #   if: always()
      #   uses: ./github/actions/slack
      #   with:
      #     slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
      #     message: Hello from PHP, Slack
      - uses: ChanManChan/open-issue@v1
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Title
          body: Body
          assignees: |
            ChanManChan
            NandaGopal1
        continue-on-error: true
      - run: |
          echo ${{ steps.issue.outputs.issue }}
      # - uses: ./.github/actions/hello
      #   id: hello
      #   with:
      #     who-to-greet: "NandaGopal Testing"
      # - name: Docker action
        # if: always()
        # uses: ./.github/actions/hello-docker
        # id: hello
        # with:
          # who-to-greet: "NandaGopal Testing Docker action"
      - name: Outputs hardcoded value
        if: always()
        run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO

# https://github.com/actions/toolkit/blob/master/docs/action-versioning.md
