on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Custom issue creator action
        uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Title
          body: Body
          assignees: |
            ChanManChan
            NandaGopal1
      - name: Output of issue creator
        run: |
          echo  ${{ steps.issue.outputs.issue }}
      - name: Custom action
        uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "Nanda uberChan gopal"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO
